//------------------------------------------------------------------------------
// <auto-generated>
//     هذا الكود تم إنشاؤه بواسطة أداة.
//     تغيير هذا الملف قد يتسبب في سلوك غير صحيح وسيتم فقدانه
//     إذا تم إعادة إنشاء الكود.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riyadh_Al_Salehin
{
    public partial class Roles
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.TextBox txtName;

        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        protected global::System.Web.UI.WebControls.HiddenField hfId;

        protected global::System.Web.UI.WebControls.Button btnNew;

        protected global::System.Web.UI.WebControls.Button btnSave;

        protected global::System.Web.UI.WebControls.Button btnUpdate;

        protected global::System.Web.UI.WebControls.Button btnDelete;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        protected global::System.Web.UI.WebControls.GridView gvRoles;

        protected global::System.Web.UI.WebControls.Panel pnlPermissions;

        protected global::System.Web.UI.WebControls.Label lblSelectedRoleName;

        protected global::System.Web.UI.WebControls.Button btnSavePermissions;

        protected global::System.Web.UI.WebControls.Repeater rptModules;

        protected global::System.Web.UI.WebControls.Label lblNoPermissions;
    }
}