//------------------------------------------------------------------------------
// <auto-generated>
//     هذا الكود تم إنشاؤه بواسطة أداة.
//     تغيير هذا الملف قد يتسبب في سلوك غير صحيح وسيتم فقدانه
//     إذا تم إعادة إنشاء الكود.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riyadh_Al_Salehin
{
    public partial class Users
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.TextBox txtPhone;

        protected global::System.Web.UI.WebControls.DropDownList ddlRole;

        protected global::System.Web.UI.WebControls.DropDownList ddlDoctor;

        protected global::System.Web.UI.WebControls.DropDownList ddlCenter;

        protected global::System.Web.UI.WebControls.CheckBox chkIsActive;

        protected global::System.Web.UI.WebControls.HiddenField hfId;

        protected global::System.Web.UI.WebControls.Button btnNew;

        protected global::System.Web.UI.WebControls.Button btnSave;

        protected global::System.Web.UI.WebControls.Button btnUpdate;

        protected global::System.Web.UI.WebControls.Button btnDelete;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        protected global::System.Web.UI.WebControls.GridView gvUsers;
    }
}